import { CustomError } from "../CustomError";

export default class InvitationNotFoundError extends CustomError {
    constructor(
        message: string = "Convite n√£o encontrado", 
        public statusCode: number = 422
    ) {
        super(message, statusCode);
        this.name = "InvitationNotFoundError";
    }
}